### ISSUE TITLE
添加引入第三方库的功能

### ISSUE THREAD

**Issue by NewbieXvwu** [eric2788/pyinstaller-build#10]
又是我来发issue啦~
这次的问题是我编译完毕的程序无法运行，因为它使用了第三方库。
在action中添加安装第三方库的功能仍无法使用。
我找到了[疑似解决方案](https://blog.csdn.net/sqylqq/article/details/104497498)，但是我不知道action中的site-packages目录在哪里。
我的[action脚本](https://github.com/NewbieXvwu/MinecraftSkinDownloader/blob/main/.github/workflows/main.yml)，[编译结果](https://github.com/NewbieXvwu/MinecraftSkinDownloader/actions/runs/1642526073)
请帮帮我，谢谢！

**Comment by eric2788** [comment]
1. 把你需要的第三庫名稱或版本(如特定) 放到 `requirements.txt` 裡面
2. 使用 action 時 輸入 `use-dependencies: true` 參數 或不填 `use-dependencies` (默認為 true)
3. 運行 action 即可

可以參考 https://github.com/eric2788/AI-project-tic-tae-toe

**Comment by NewbieXvwu** [comment]
我用另外一种方式解决了问题（为此我Fork了您的仓库），谢谢！
