### ISSUE TITLE
Feature request: custom icon

### ISSUE THREAD

**Issue by roggif** [eric2788/pyinstaller-build#3]
Could you implement a way to let the user select a custom icon for the packaged file?

The docs for the required argument are [these ones](https://pyinstaller.readthedocs.io/en/stable/usage.html#cmdoption-i).

Thanks in advance.

**Comment by eric2788** [comment]
I am kind of busy so maybe later, or you can create a PR (better make as input)

**Comment by roggif** [comment]
Yeah, no need to rush it, take your time.

If I have some spare time I can make a PR later today.

**Comment by eric2788** [comment]
@zzkW35 hey, can you try with using `eric2788/pyinstaller-build@patch/icon` ? I have not tested it yet
