### ISSUE TITLE
支持pyw格式

### ISSUE THREAD

**Issue by NewbieXvwu** [eric2788/pyinstaller-build#8]
由于我看见您的一些项目使用了中文，所以我使用中文撰写此issue。
我制作了一个pyw格式的程序，但是似乎无法使用您的工具来构建。我的仓库地址：https://github.com/NewbieXvwu/MinecraftSkinDownloader  ，希望您能给予一些帮助（我真的完全不懂Github Action），并为您的工具添加pyw格式的支持。谢谢！

**Comment by NewbieXvwu** [comment]
现在可以成功地构建了，但是请问构建成功后我怎样才能让它自动输出一个编译成功的文件？

**Comment by eric2788** [comment]
首先，使用後綴 `.pyw` 的目的是為了防止輸出 console (指令視窗), 而本 action 是擁有防止輸出 console 的視窗參數 `no-console`, 所以我不認為會構成衝突,你改回 `.py` 即可

**Comment by eric2788** [comment]
關於如何使用請到 [test-actions.yml](https://github.com/eric2788/pyinstaller-build/blob/master/.github/workflows/test-actions.yml) 查看

**Comment by NewbieXvwu** [comment]
我已经成功构建了。谢谢！
