### ISSUE TITLE
想知道如何让用户在构建后能下载构建的文件

### ISSUE THREAD

**Issue by NewbieXvwu** [eric2788/pyinstaller-build#9]
如题，我是个action新手，我想知道如何才能让用户在构建后下载成功构建的文件。谢谢！

**Comment by eric2788** [comment]
可以參考我過往的python專案，例如: https://github.com/eric2788/AI-project-tic-tae-toe/blob/master/.github/workflows/download.yaml

以上執行完成 actions 上的 artifact 就會出現檔案，但如果要推上 releases 則有點複雜:

https://github.com/eric2788/BiliLiveBot/blob/master/.github/workflows/publish.yml (upload release 部分)

但詳細還是要你自己去查看 github action 的文檔

**Comment by NewbieXvwu** [comment]
成功了。谢谢！
